FROM openjdk:8-jre-alpine

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /app/logs /app/conf
WORKDIR /app
COPY target/mhealth-server-1.0-SNAPSHOT.jar app.jar
COPY docker-mhealth.properties default.properties
COPY docker-log4j.xml log4j.xml

VOLUME /app/conf /app/logs
EXPOSE 8080

CMD ["java", \
     "-Dlog4j.configuration=file:/app/log4j.xml", \
     "-Dlocal.properties=/app/conf/app.properties:/app/default.properties", \
     "-jar","app.jar", \
     "mhealth"]
