apiVersion: v1
kind: ConfigMap
metadata:
  name: mhc-fluentd-config
data:
  fluentd.conf: |
    <source>
       @type tail
       path /app/logs/app.log
       pos_file /app/logs/app.pos
       read_from_head true
       tag mhc-app
       format multiline
       format_firstline /\d{2}:\d{1,2}:\d{1,2},\d{1,3}/
       format1 /(?<message>.*)/
    </source>

    <source>
       @type tail
       path /app/logs/poll.log
       pos_file /app/logs/poll.pos
       read_from_head true
       tag mhc-poll
       format multiline
       format_firstline /\d{2}:\d{1,2}:\d{1,2},\d{1,3}/
       format1 /(?<message>.*)/
    </source>

    <match **>
      @type google_cloud
    </match>
